### ISSUE TITLE
High Mining Fatigue Crashes

### ISSUE THREAD

**Issue by Charles445** [fnar/minecraft-roguelike#11]
Roguelike Dungeons adds equipment to mobs that join the world with mining fatigue on them.
This is to help its spawners out, but this effect also happens to mobs that have already spawned in. As long as they had mining fatigue when they unloaded, they will get equipped when they reload.

Unfortunately, with high mining fatigue values (5+ or so), the game will crash.
This is usually a NullPointerException over in greymerk.roguelike.treasure.loot.Quality.getToolQuality

This doesn't really happen in vanilla, but it does happen in heavily modded environments, so I wanted to let you know about it before it causes any trouble in this new fork.

**Comment by srwaggon** [comment]
@Charles445 Thanks for the heads up! This is a wonderful find.

Do you by chance have any examples of mods/modpacks where I could recreate this issue?

**Comment by Charles445** [comment]
RLCraft, there's an enchantment called "Freezing", put it on a weak weapon of some sort.
Attack a zombie with it until it applies twice (you can tell by the noise it makes), then save and quit to title screen, then load the save again. If done correctly it'll crash.
