### ISSUE TITLE
[Suggestion] The non-used tower and dungeons styles could be used to spawn

### ISSUE THREAD

**Issue by BugmanBugman** [fnar/minecraft-roguelike#19]
looking at the curseforge page and wiki, I noticed that there are lots of styles that aren't used. I think they are too good to pass up as just alternative options for the config. not many people know how to work a config either. more towers and dungeons could add more of a diverse experience.

**Comment by srwaggon** [comment]
It's a dream of mine to add more builtin dungeons once I wrangle this codebase more.

**Comment by EnderBro123** [comment]
> It's a dream of mine to add more builtin dungeons once I wrangle this codebase more.

You have 12 open issues...

**Comment by BugmanBugman** [comment]
Classic ender slime being toxic for no reason. Are you gonna threaten for him to delete it?

**Comment by EnderBro123** [comment]
I didn't say that I was.

**Comment by srwaggon** [comment]
There's a strong possibility I'll be getting around to this soon.

In the meantime, I'd like to kindly remind that the mod is highly configurable and that the towers are already accessible via configurations. 😃

Happy adventuring!

**Comment by fnar** [comment]
Closing this as there are a handful of ways to acquire the alternative towers.

Users are capable of enabling the 'random' configuration, which will generate entirely random dungeons with all possible options, or they can manually configure dungeons using the towers they wish to see.
