### ISSUE TITLE
[Bug/Suggestion] Make dungeons not collide with YOUNG's BetterCaves or Worley's Caves cave gen.

### ISSUE THREAD

**Issue by MagmaBro123** [fnar/minecraft-roguelike#27]
Title says all.

![2020-12-15_11 18 37](https://user-images.githubusercontent.com/51277766/102262036-63e07300-3ec7-11eb-9df6-762cfca21687.png)
![2020-12-15_11 18 48](https://user-images.githubusercontent.com/51277766/102262043-65aa3680-3ec7-11eb-9a4a-60454dd538d2.png)
![2020-12-15_11 19 04](https://user-images.githubusercontent.com/51277766/102262046-6642cd00-3ec7-11eb-9199-b031c69221c0.png)

**Comment by fnar** [comment]
Closing this as there's no currently known solid way to detect where one chunk generating mod will conflict with another chunk generating mod.

I'm open to suggestions and re-opening this issue if a great solution is provided by the community.

**Comment by MagmaBro123** [comment]
Closing this won't make people notice it that easily without switching to the Closed issues tab..
