### ISSUE TITLE
Oak Saplings are dropping from the leaf-themed dungeons and causing MASSIVE lag.

### ISSUE THREAD

**Issue by roccscout** [fnar/minecraft-roguelike#53]
Title.

The leaf-themed dungeons are cool, but the oak leaves decay (likely due to another mod I have? not sure).
When they decay, they drop saplings EVERYWHERE and it causes massive lag... massive.

Any ideas how to fix?

**Comment by srwaggon** [comment]
Edit: This can't yet be solved. I recommend removing leaves from the theme for the time being.
---

Thanks for the report, @roccscout. Reports like this ensure increased quality and improved experience for everyone. ♥

I think I have an idea. Hopefully I can find the time to get around to it.

I'm making an assumption that you're using the provided settings from here:
https://github.com/fnar/minecraft-roguelike-settings

If this is true, then the "settings" file which specifies to generate leaves comes from here:
https://github.com/fnar/minecraft-roguelike-settings/blob/master/fnar/vanilla/theme/theme_forest.json

Briefly cross-referencing the data values for leaves, there appears to be a property `persistent` which tells the leaves not to decay even when there are no wood blocks nearby. This property's value appears to be `false` by default, leading to natural decay.

By adding this property and a default value of true to the forest theme, I imagine we can prevent the decay and prevent the lag.

That is -- for everywhere that the theme says
```json
{"type" : "METABLOCK", "data" : {"name" : "leaves"}, "weight" : 5}
```

convert it into...
-- Ah bummer. It appears this can't be done yet with the current version of the app. For now, maybe just remove the lines with refer to leaves from the theme. 😟 I'll take this as a future improvement.

**Comment by fnar** [comment]
@roccscout An easy maneuver would be to simply remove the forest dungeons, or forest theme, from your configs. Anywhere that the forest theme is referenced would need to be replaced with another theme, or else a default theme will be used.

**Comment by fnar** [comment]
It would be wonderful to abstract the concept of block states for [metablocks](https://github.com/fnar/minecraft-roguelike/wiki/BlockFactory#metablock) such that they can be provided as part of a block factory and attached to the metablock.

This would be an incredibly large effort to make block states general enough to attach to any block and still convert correctly into their Forge counterparts. It's unlikely to happen any time soon.
