### ISSUE TITLE
structure issues about stairs in cellings

### ISSUE THREAD

**Issue by touhouzun** [fnar/minecraft-roguelike#60]
RoguelikeDungeonsFnarEdition-1.12.2-2.4.0
![2021-07-29_09 43 05](https://user-images.githubusercontent.com/31458903/127420057-92ac2158-6cb8-4a32-9b4d-bf827d0a31aa.png)
![2021-07-29_09 56 59](https://user-images.githubusercontent.com/31458903/127420067-4c0c74f8-7165-4dad-ad71-e7746944272d.png)
![2021-07-29_09 57 27](https://user-images.githubusercontent.com/31458903/127420073-9e80f82b-33b9-4b71-a1b6-36e8fbe21021.png)
![2021-07-29_09 58 06](https://user-images.githubusercontent.com/31458903/127420077-fe106a36-abf7-460c-8b28-e007a5ca0855.png)
![2021-07-29_09 59 03](https://user-images.githubusercontent.com/31458903/127420078-787eb016-df4e-4978-8bb7-0351336edb11.png)
![2021-07-29_10 00 16](https://user-images.githubusercontent.com/31458903/127420091-2138c747-36d1-4bfb-88ac-167b1ac87bcc.png)

Spawners are may designed like this, but those stairs in cellings...
Anyway, is it possible to make a defalut theme which changes gravel/sand in those dungeons into no-falling solid blocks?
Look at this snow-themed dungeon, neat, nice, and clean.
Well gravel in cobweb room...nevermind :)

**Comment by fnar** [comment]
Thanks for this wonderful report, @touhouzun. Which version of the mod are you currently using?

**Comment by fnar** [comment]
Some themes use gravel in their wall/floor block selections. Since the mod is configurable, you can change these dungeons to only use themes that do not employ gravel.

The cobweb room specifically uses gravel as well to be annoying. Since it was designed that way in the original mod, I'm hesitant to change it. :s

**Comment by touhouzun** [comment]
> Thanks for this wonderful report, @touhouzun. Which version of the mod are you currently using?

RoguelikeDungeonsFnarEdition-1.12.2-2.4.0 ,newest, sir.
