### ISSUE TITLE
Structures not generating loot

### ISSUE THREAD

**Issue by mikesk8r** [fnar/minecraft-roguelike#74]
i have roguelike dungeons fnar edition and ~70 or so other mods installed on forge 1.12.2 on macos.
the problem is that all of the chests generated are empty even though i am using the default configs minus the modpack ones and most of the mod ones too.

let me know if you need the config file/mod list/etc

**Comment by fnar** [comment]
Did you ever solve this issue? I suspect it is configuration on your end as the mod current appears to be working.

**Comment by fnar** [comment]
Closing due to abandonment.
