### ISSUE TITLE
[2.4.5 INDEV] Dungeon gen crash (java.lang.VerifyError: Bad type on operand stack)

### ISSUE THREAD

**Issue by KameiB** [fnar/minecraft-roguelike#92]
Created a new world and used today's INDEV compile.  
Flew over the world and game crashed 😥
`Type 'com/github/fnar/minecraft/item/Arrow' (current frame, stack[1]) is not assignable to 'com/github/fnar/minecraft/item/RldBaseItem'`

Probably caused by  7565d3b.

Attached crash log:
[crash-2024-08-10_22.41.46-server.txt](https://github.com/user-attachments/files/16571485/crash-2024-08-10_22.41.46-server.txt)

**Comment by fnar** [comment]
😭

**Comment by fnar** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠠⠀⠚⠉⠉⠈⠀⠀⠀⠀⠀⠀⠀⠉⠁⠐⠀⠄⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠄⠂⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠐⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⢠⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠢⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢦⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠄⠀⠀⠀
⠀⠀⠠⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠄⠀⠀
⠀⢠⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠄⠀
⢀⠂⠀⠀⠀⠀⠀⠀⢀⣀⣴⣾⣿⣿⡿⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⢿⣿⣿⣷⣦⣄⡀⠀⠀⠀⠀⠀⠀⠐⡀
⡞⠀⠀⠀⠀⠀⠠⣾⣿⣿⣿⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠁
⡇⠀⠀⠀⠀⠀⠀⠉⠛⠉⢀⣀⣠⣤⣤⣤⣤⣤⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣤⣤⣤⣀⡀⠉⠛⠉⠀⠀⠀⠀⠀⠀⠘
⠁⠀⠀⠀⠀⠀⠀⠀⣰⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡆⠀⠀⠀⠀⠀⠀⠀⠈
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠋⣏⠰⠀⢆⡐⢸⠀⠈⠉⠛⠋⠀⠀⠀⠀⠀⠀⠙⠛⠉⠁⠀⣇⠰⡀⠆⠤⢹⠙⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⢢⠉⡂⢄⢻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣇⠢⠑⡌⢢⠹⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀
⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⠄⡃⠌⢢⢸⠀⠀⠀⠀⠀⠀⣀⣤⣤⣀⠀⠀⠀⠀⠀⠀⡧⢘⠰⡈⠆⢹⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠
⣳⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣏⠐⡁⠎⡐⣸⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⡗⡈⠤⡑⠌⢺⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀
⠁⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⣇⠘⠤⡑⠄⣹⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⡗⡈⠆⡱⢈⠼⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠀
⠀⠘⡀⠀⠀⠀⠀⠀⠀⠀⠀⡧⠘⡄⠢⡑⢸⠀⠀⢠⣿⣿⣿⡿⣿⢿⡿⣿⣿⣿⡄⠀⠀⡗⢨⠐⡡⠊⢼⠀⠀⠀⠀⠀⠀⠀⠀⢀⠂⠀
⠀⠀⠐⡀⠀⠀⠀⠀⠀⠀⠀⡧⢁⠆⡡⢘⢸⠀⠀⢼⣿⣿⣳⢿⣹⢯⣽⣳⣟⣿⡇⠀⠀⡏⠤⡑⢄⠋⣜⠀⠀⠀⠀⠀⠀⠀⢀⠂⠀⠀
⠀⠀⠀⠈⢄⠀⠀⠀⠀⠀⠀⣇⠂⢆⡁⠆⢺⠀⠀⠸⣿⣷⣯⢿⣹⣟⡾⣳⣿⣿⠇⠀⠀⡏⠔⡈⢆⠡⢸⠀⠀⠀⠀⠀⠀⡠⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠡⡀⠀⠀⠀⠀⡧⠘⠄⡂⢍⢸⠀⠀⠀⠙⠻⠿⠿⠿⠿⠿⠿⠟⠋⠀⠀⠀⣏⠰⢁⠎⣐⢩⠀⠀⠀⠀⢀⠔⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⠢⣀⠀⠀⡧⠑⡊⡐⢂⢹⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠒⡌⠒⡄⢺⠀⠀⢀⠴⠁⠀⠀⠀⠀⠀⠀
⠀⠀⢀⡀⢀⠠⠤⠈⠨⢀⠐⠣⡑⠄⡑⡨⠘⠒⢒⡀⠆⠰⠠⠡⠌⡁⠆⢡⠐⡀⠆⠒⠒⡋⠔⡠⢃⠂⡍⠂⠴⢁⠀⠠⢄⠀⢀⡀⠀⠀
⡢⢇⠈⠤⠉⡄⢃⠌⠱⡈⠌⡑⠠⠃⠜⣀⠣⢉⠢⡐⢌⠡⣁⠣⡐⢡⠘⡄⢊⠔⡨⢁⠣⡐⠡⢂⠅⠣⢐⠉⠢⠌⡂⠍⢂⠌⡐⠌⢨⣐
⠀⠉⠈⠒⠃⠐⠬⠌⠥⠐⠡⣌⣑⣌⢒⣀⠆⢡⠒⡈⡄⠣⢄⠃⡔⢡⠊⡄⠣⢌⠰⡁⢂⠡⣑⡂⣌⣑⣨⠬⠡⠜⠠⠮⠴⠎⠚⠚⠉⠉

**Comment by KameiB** [comment]
Only you have the power to save us! 🙏

**Comment by KameiB** [comment]
It was a me problem.
Didn't build in the correct order.
 Sorry to bother!
